# Generated by Django 2.0.6 on 2018-09-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('yes', models.IntegerField(default=0)),
                ('no', models.IntegerField(default=0)),
            ],
        ),
    ]
