# Generated by Django 2.0.6 on 2018-09-09 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='no',
            new_name='no_count',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='yes',
            new_name='yes_count',
        ),
        migrations.CreateModel(
            name='NoArgument',
            fields=[
                ('argument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alfa.Argument')),
            ],
            bases=('alfa.argument',),
        ),
        migrations.CreateModel(
            name='YesArgument',
            fields=[
                ('argument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alfa.Argument')),
            ],
            bases=('alfa.argument',),
        ),
    ]
