# Generated by Django 2.0.6 on 2018-09-09 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0002_auto_20180909_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='noargument',
            name='theme',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_arguments', to='alfa.Theme'),
        ),
        migrations.AddField(
            model_name='yesargument',
            name='theme',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yes_arguments', to='alfa.Theme'),
        ),
    ]
