# Generated by Django 2.0.6 on 2018-09-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0003_auto_20180909_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
