# Generated by Django 2.0.6 on 2018-09-09 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alfa', '0004_auto_20180909_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='user',
            field=models.ManyToManyField(default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
