# Generated by Django 2.0.6 on 2018-09-09 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0005_argument_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='argument',
            name='user',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
