# Generated by Django 2.0.6 on 2018-09-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0006_auto_20180909_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
