# Generated by Django 2.0.6 on 2018-09-09 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alfa', '0007_argument_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='argument',
            options={'ordering': ['-number_of_likes', '-datetime']},
        ),
        migrations.AddField(
            model_name='argument',
            name='liked_by',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='argument',
            name='number_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='argument',
            name='user',
            field=models.ManyToManyField(related_name='arguments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='argument',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='alfa.Argument'),
        ),
    ]
