# Generated by Django 2.0.6 on 2018-10-09 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('russianseasons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprototype',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
    ]
