# Generated by Django 2.0.6 on 2018-10-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('russianseasons', '0003_auto_20181009_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprototype',
            name='categories',
            field=models.ManyToManyField(to='russianseasons.Category'),
        ),
        migrations.AlterField(
            model_name='itemprototype',
            name='colors',
            field=models.ManyToManyField(to='russianseasons.Color'),
        ),
        migrations.AlterField(
            model_name='itemprototype',
            name='images',
            field=models.ManyToManyField(to='russianseasons.Image'),
        ),
        migrations.AlterField(
            model_name='itemprototype',
            name='sizes',
            field=models.ManyToManyField(to='russianseasons.Size'),
        ),
    ]
