# Generated by Django 2.0.6 on 2018-10-09 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('russianseasons', '0005_auto_20181009_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprototype',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
