# Generated by Django 2.1.2 on 2018-10-20 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('russianseasons', '0007_auto_20181017_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemprototype',
            name='images',
        ),
        migrations.AddField(
            model_name='itemprototype',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
