# Generated by Django 2.1.2 on 2018-10-21 11:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('russianseasons', '0008_auto_20181020_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='prototype',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='russianseasons.ItemPrototype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='city', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='email', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemprototype',
            name='image',
            field=models.ImageField(upload_to='img/items/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_preorder',
            field=models.BooleanField(default=True),
        ),
    ]
