# Generated by Django 2.1.2 on 2018-10-21 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('russianseasons', '0009_auto_20181021_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='prototype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='russianseasons.ItemPrototype'),
        ),
    ]
