# Generated by Django 2.1.2 on 2018-11-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('russianseasons', '0017_storage_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='value',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
